6apiVersion: v1
kind: ConfigMap
metadata:
  name: chartversion
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  CHART_VERSION: quixcontainerregistry.azurecr.io/helm/quixplatform-manager:1.5.4
